services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: ./temp-app
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
